#!/usr/bin/env python3
"""Turn the string catalog into something a translator can work from, and back into C.

Two subcommands:

  template [-o FILE]     every entry as msgid/msgctxt/msgstr, in a gettext-like .pot
  stub LANG [-o FILE]    a src/i18n/locale_LANG.c ready to have translations pasted into

Both read include/mesh/i18n/catalog.def, which is the only description of the catalog there is
- the enum, the English table and these outputs are all expansions of that one list, so they
cannot drift.

Neither is part of the build. Run one by hand when you want it, the way scripts/gen-emoji.py
is run by hand; a stub is committed once and then edited like any other source file.

  ./scripts/gen-locale.py template -o meshclient.pot
  ./scripts/gen-locale.py stub de -o src/i18n/locale_de.c
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "include/mesh/i18n/catalog.def"

ENTRY = re.compile(r"^MESH_STR_ENTRY\(\s*([A-Z0-9_]+)\s*,\s*(\".*\")\s*\)\s*$")
PLURAL = re.compile(r"^MESH_STR_PLURAL_ENTRY\(\s*([A-Z0-9_]+)\s*,\s*(\".*?\")\s*,\s*(\".*\")\s*\)\s*$")
COMMENT_LINE = re.compile(r"^\s*(?:/\*+|\*+/?|//)?\s?(.*?)\s*(?:\*/)?\s*$")


def read_catalog():
    """[(id, C-quoted text, comment)] in catalog order, plural entries expanded to _ONE/_OTHER.

    The comment is whatever block or line comment immediately precedes the entry, which is
    where a translator is told what a string is for; it is carried into both outputs, because
    a string with no context is a string that gets translated wrong.
    """
    entries = []
    pending = []
    in_block = False
    for raw in CATALOG.read_text().split("\n"):
        line = raw.rstrip()
        stripped = line.strip()
        if not stripped:
            pending = []
            continue

        if in_block:
            pending.append(COMMENT_LINE.match(stripped).group(1))
            if "*/" in stripped:
                in_block = False
            continue
        if stripped.startswith("/*"):
            pending.append(COMMENT_LINE.match(stripped).group(1))
            in_block = "*/" not in stripped
            continue

        match = ENTRY.match(stripped)
        if match:
            entries.append((match.group(1), match.group(2), pending))
            pending = []
            continue
        match = PLURAL.match(stripped)
        if match:
            note = pending + ["Plural: this form is used when the locale's rule selects it."]
            entries.append((match.group(1) + "_ONE", match.group(2), note))
            entries.append((match.group(1) + "_OTHER", match.group(3), note))
            pending = []
            continue
        # A MESH_STR_ line that matched neither is a line this parser has lost, and losing one
        # silently means a translator never sees that string. Say so rather than carrying on.
        if stripped.startswith("MESH_STR_"):
            raise SystemExit(f"catalog.def line {raw!r} is not an entry this script can read")
        pending = []
    return entries


def clean(lines):
    """Drop the decorative rule lines and blank padding from a carried-over comment."""
    kept = [line for line in lines if line and set(line) - set("- ")]
    return kept


def template(entries, out):
    out.write(
        "# MeshClient user-facing strings.\n"
        "#\n"
        "# Generated from include/mesh/i18n/catalog.def by scripts/gen-locale.py; do not edit\n"
        "# this file expecting the client to read it. Translate msgstr, then move the results\n"
        "# into a src/i18n/locale_<id>.c table (./scripts/gen-locale.py stub <id>).\n"
        "#\n"
        "# Keep every %-specifier, in the same order and of the same type, as the msgid has.\n"
        "# The words around them are yours to reorder; the specifiers are what the code passes\n"
        "# and mesh_i18n_validate() rejects a mismatch before it can crash anything.\n"
        "#\n"
        "# msgctxt is the catalog id. It, not the English, is what identifies a string.\n"
        "\n"
        'msgid ""\n'
        'msgstr ""\n'
        '"Content-Type: text/plain; charset=UTF-8\\n"\n'
        "\n"
    )
    for name, text, comment in entries:
        for line in clean(comment):
            out.write(f"#. {line}\n")
        out.write(f'msgctxt "{name}"\n')
        out.write(f"msgid {text}\n")
        out.write('msgstr ""\n\n')


def stub(entries, language, out):
    out.write(
        f"""/*
 * {language}: the catalog, translated.
 *
 * Generated by scripts/gen-locale.py and then edited by hand - it is ordinary source from the
 * moment it is committed, and regenerating it would throw the translations away. When the
 * catalog grows, add the new ids here; anything missing is not an error, it reads as English.
 *
 * Keep every %-specifier the English has, in the same order and of the same type. The words
 * around them are yours. mesh_i18n_validate() checks this over every locale in the tests.
 *
 * To ship it: add the file to CMakeLists.txt and a row to k_locales in src/i18n/strings.c.
 * See docs/i18n.md.
 */

#include "mesh/i18n/strings.h"

const char *const mesh_i18n_table_{language}[MESH_STR_COUNT] = {{
"""
    )
    for name, text, comment in entries:
        for line in clean(comment):
            out.write(f"    /* {line} */\n")
        out.write(f"    /* en: {text} */\n")
        out.write(f"    [MESH_STR_{name}] = NULL,\n")
    out.write("};\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    one = sub.add_parser("template", help="a gettext-like .pot for a translator")
    one.add_argument("-o", "--output", help="write here instead of stdout")
    two = sub.add_parser("stub", help="a src/i18n/locale_<lang>.c skeleton")
    two.add_argument("language", help="the locale id, e.g. de")
    two.add_argument("-o", "--output", help="write here instead of stdout")
    args = parser.parse_args()

    entries = read_catalog()
    if not entries:
        print("no entries found; is catalog.def where it was?", file=sys.stderr)
        return 1

    out = open(args.output, "w") if args.output else sys.stdout
    try:
        if args.command == "template":
            template(entries, out)
        else:
            stub(entries, args.language, out)
    finally:
        if args.output:
            out.close()
    if args.output:
        print(f"{len(entries)} entries -> {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
