#!/usr/bin/env python3
"""Turn Mozilla's CA bundle into the root table compiled into the binary.

This is not part of the build. Run it by hand when the bundle is refreshed and commit the
generated file, so the build stays dependency-free and CI never reaches the network:

    curl -sSLo Tools/tg5040/MeshClient.pak/certs/certificates.crt https://curl.se/ca/cacert.pem
    python3 scripts/gen-ca-roots.py

`--check` regenerates in memory and fails if the committed table no longer matches the bundle,
which is what `make test` runs: the pak's file is what curl verifies against and the table is what
Mbed TLS verifies against, and the two answering differently would be two clients in one binary.

Why the roots are in the binary at all: the Brick has no system certificate store, and a file in
the pak does not ship through self-update - so an install keeps whatever roots its original pak
carried, for as long as it is updated in place. The day a CA that GitHub or a broker chains to is
rotated out of that file, the connection that fails is the one the fix would arrive over. Compiled
in, the roots are refreshed by every release.

DER rather than PEM: it is what Mbed TLS parses without a copy (`mbedtls_x509_crt_parse_der_nocopy`
keeps pointers into the table instead of duplicating it on the heap), and it is a third smaller.
"""

import argparse
import base64
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_INPUT = ROOT / "Tools/tg5040/MeshClient.pak/certs/certificates.crt"
DEFAULT_OUTPUT = ROOT / "src/core/generated/ca_roots.c"

BLOCK = re.compile(
    r"-----BEGIN CERTIFICATE-----\s*(.*?)\s*-----END CERTIFICATE-----", re.DOTALL
)
AS_OF = re.compile(r"^## Certificate data from Mozilla as of: (.+)$", re.MULTILINE)


def read_bundle(text):
    """(label, der) per certificate, in file order.

    The label is the line mk-ca-bundle.pl writes above the `====` underline; a bundle without
    one - hand-assembled, or from another tool - is labelled by position instead.
    """
    roots = []
    for match in BLOCK.finditer(text):
        der = base64.b64decode("".join(match.group(1).split()), validate=True)
        before = text[: match.start()].rstrip("\n").split("\n")
        label = ""
        if len(before) >= 2 and before[-1] and set(before[-1]) == {"="}:
            label = before[-2].strip()
        roots.append((label or f"root {len(roots)}", der))
    return roots


def c_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(roots, as_of):
    total = sum(len(der) for _, der in roots)
    out = [
        "/*",
        " * Generated by scripts/gen-ca-roots.py from Mozilla's CA bundle - do not edit by hand.",
        " *",
        f" * {len(roots)} roots, {total} bytes of DER. Certificate data from Mozilla as of",
        f" * {as_of}, as extracted by curl's mk-ca-bundle.pl.",
        " *",
        " * The certificate data is subject to the terms of the Mozilla Public License, v. 2.0. If a",
        " * copy of the MPL was not distributed with this file, you can obtain one at",
        " * https://mozilla.org/MPL/2.0/.",
        " */",
        "",
        '#include "mesh/core/ca_roots.h"',
        "",
        "/* Every root's DER, one after another. */",
        "static const unsigned char k_der[] = {",
    ]
    blob = b"".join(der for _, der in roots)
    for at in range(0, len(blob), 16):
        out.append("    " + " ".join(f"0x{b:02X}," for b in blob[at : at + 16]))
    out.append("};")
    out.append("")
    out.append("const struct mesh_ca_root mesh_ca_roots[] = {")
    offset = 0
    for label, der in roots:
        out.append(f"    {{{c_string(label)}, k_der + {offset}, {len(der)}}},")
        offset += len(der)
    out.append("};")
    out.append("")
    out.append(f"const size_t mesh_ca_root_count = {len(roots)};")
    out.append("")
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("input", nargs="?", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("output", nargs="?", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed table does not match the bundle")
    args = parser.parse_args()

    text = args.input.read_text(encoding="utf-8")
    roots = read_bundle(text)
    if not roots:
        sys.exit(f"{args.input}: no certificates")
    as_of = AS_OF.search(text)
    rendered = render(roots, as_of.group(1).strip() if as_of else "an unrecorded date")

    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if current != rendered:
            rel_in = args.input.relative_to(ROOT) if args.input.is_absolute() else args.input
            sys.exit(f"{args.output.relative_to(ROOT)} is stale against {rel_in}: "
                     "run scripts/gen-ca-roots.py and commit the result")
        return
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"{len(roots)} roots -> {args.output}")


if __name__ == "__main__":
    main()
