#ifndef MESH_UI_EMOJI_H
#define MESH_UI_EMOJI_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Colour emoji sprites for the framebuffer backend.
 *
 * Meshtastic names are written by people, and on a real mesh a good share of nodes are named
 * entirely in emoji - `User.short_name` is `char[5]`, which holds exactly one. Without these a
 * node like that draws as a row of replacement boxes and cannot be told apart from any other.
 *
 * The data is generated by scripts/gen-emoji.py from Noto Color Emoji and committed; the build
 * never rasterises anything. Each sprite is MESH_EMOJI_SIZE square, one byte of palette index
 * per pixel, run-length encoded - emoji are mostly flat fills inside a transparent margin, so
 * the runs cost a fraction of the raw pixels.
 */

#define MESH_EMOJI_SIZE 16

/* Index 0 means transparent; a stored index N is palette entry N - 1. */
#define MESH_EMOJI_TRANSPARENT 0

struct mesh_emoji_single {
    uint32_t codepoint;
    uint16_t sprite;
};

struct mesh_emoji_sequence {
    uint32_t first;      /* leading codepoint, the key this table is sorted on */
    uint16_t tail;       /* offset into sequence_tail of the codepoints after the first */
    uint8_t length;      /* codepoints in the whole sequence, including the first */
    uint16_t sprite;
};

struct mesh_emoji_table {
    const uint8_t (*palette)[3];
    uint16_t palette_size;
    /* Flat (count, index) pairs; run N is runs[N * 2] and runs[N * 2 + 1]. */
    const uint8_t *runs;
    const uint32_t *run_offsets;
    const struct mesh_emoji_single *singles;
    uint32_t single_count;
    const struct mesh_emoji_sequence *sequences;
    uint32_t sequence_count;
    const uint32_t *sequence_tail;
    uint8_t longest_sequence;
};

extern const struct mesh_emoji_table mesh_emoji_table;

/*
 * Longest emoji starting at codepoints[0]. Returns how many codepoints it consumed - 0 when
 * none of them start an emoji - and stores the sprite id in *sprite.
 *
 * Greedy on purpose: a regional-indicator pair is a flag rather than two letters, and a ZWJ
 * sequence is one glyph rather than its parts, so the longest match is the right one.
 */
size_t mesh_emoji_match(const uint32_t *codepoints, size_t count, uint16_t *sprite);

/* Expand `sprite` into one palette index per pixel, row by row. Index 0 is transparent.
   Callers decode once and then index, rather than walking the runs per pixel. */
void mesh_emoji_decode(uint16_t sprite, uint8_t out[MESH_EMOJI_SIZE * MESH_EMOJI_SIZE]);

/* Colour behind a decoded index. Returns false for the transparent index. */
bool mesh_emoji_color(uint8_t index, uint8_t rgb[3]);

/* Codepoints that attach to the character before them and never take a cell of their own:
   variation selectors, skin-tone modifiers, the zero-width joiner, combining marks. Absorbing
   these is what stops an emoji written as base plus modifier - the common spelling, and the
   only spelling for things like U+26F0 U+FE0F - from drawing as two cells. */
bool mesh_emoji_is_zero_width(uint32_t codepoint);

/*
 * One drawable cell of a UTF-8 string.
 *
 * A cell is not a byte and not always a codepoint: a flag is a pair of regional indicators, a
 * family is a ZWJ sequence, and a modifier attaches to whatever came before it. Layout and
 * drawing both walk cells, through the same function, so a line always measures as wide as it
 * draws.
 */
struct mesh_ui_text_cell {
    size_t bytes;       /* source bytes consumed; 0 at the end of the string */
    bool is_emoji;
    uint16_t sprite;    /* when is_emoji */
    uint32_t codepoint; /* when not */
};

struct mesh_ui_text_cell mesh_ui_text_cell_next(const char *text);

/* Cells a string occupies once drawn. */
size_t mesh_ui_text_cells(const char *text);

/* Byte offset of cell `index`, or of the NUL when the string is shorter. */
size_t mesh_ui_text_cell_offset(const char *text, size_t index);

/* Truncate in place to at most `cells` cells, never inside one. */
void mesh_ui_text_cell_truncate(char *text, size_t cells);

#ifdef __cplusplus
}
#endif

#endif /* MESH_UI_EMOJI_H */
