#ifndef MESH_UI_ICON_H
#define MESH_UI_ICON_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Monochrome icon sprites, drawn in whatever colour the theme says.
 *
 * The UI used to mark every row with a character: "> " for a row that opens something, "* " for
 * an unsaved edit, "#" for a channel, "+" for a new message, "*" for the connected device. They
 * are readable once somebody has learnt them and invisible until then, they cost a text column
 * each, and they cannot say anything a keyboard cannot type. An icon in the same slot is read
 * without being learnt, which is why every phone and desktop platform puts one there.
 *
 * These are *not* emoji, and the difference is the whole point of a second sprite table:
 *
 *   - An emoji carries its own colours (include/mesh/ui/emoji.h) - the red of a flag is most of
 *     what makes it recognisable at 20 px. An icon carries coverage only, and takes the ink of
 *     whatever it is standing in for: a chevron on a selected row is the selected row's colour,
 *     an unsaved dot is the accent, a warning is the bad tone. It is themed like text, because
 *     it is doing text's job.
 *   - An emoji is looked up by codepoint, because it arrives inside a name somebody typed. An
 *     icon is named by the UI (MESH_UI_ICON_CHEVRON), because it is chosen by a renderer.
 *
 * Coverage is 4 bits per pixel - 0 is nothing, 15 is solid - which is what lets a sprite be
 * resampled into a cell of any size without the stepped edges a 1-bit mask would give. The
 * sprites are 32 px square, comfortably above the 24 px cell they usually land in and still
 * sharp at the several-times-body-text size an empty screen draws one at; the whole set is
 * about 15 KB. The data is generated by scripts/gen-icons.py from Material Symbols Rounded and
 * committed, so the build rasterises nothing and never reaches the network; the catalog it is
 * generated from is include/mesh/ui/icons.def.
 */

#define MESH_UI_ICON_SIZE 32
#define MESH_UI_ICON_MAX_ALPHA 15

/*
 * What a sprite is a picture *of*, in Material's own grid units - which is what a renderer needs
 * to turn "this icon is 32 px of data" into "this icon should be drawn this big".
 *
 * Material draws a symbol on a 24 square and keeps it inside the central 20, so the 20 is the
 * part that carries the shape and the ring around it is air by design. A sprite holds a little
 * more than the 24 - MESH_UI_ICON_WINDOW - because at the fill and weight these are rasterised
 * at, the full-bleed symbols (`hub`, the antenna, the warning triangle) reach the grid's edge and
 * a hair past it; a window that cuts one cuts it on every screen it appears on.
 *
 * So a renderer that wants a symbol to stand as tall as some measurement - the capitals beside
 * it, say - scales that measurement by WINDOW / BODY to get the box to draw the whole sprite in.
 * The air comes out where air belongs, around the outside.
 */
#define MESH_UI_ICON_WINDOW 256
#define MESH_UI_ICON_BODY 200

/*
 * Every icon this build can draw.
 *
 * MESH_UI_ICON_NONE is 0 and draws nothing, which is what makes an icon slot safe to leave
 * zeroed: a widget's leading slot is declared once for a whole list and the rows that have
 * nothing to put in it say so by saying nothing.
 */
enum mesh_ui_icon {
    MESH_UI_ICON_NONE = 0,
#define MESH_ICON_ENTRY(id, glyph) MESH_UI_ICON_##id,
#include "mesh/ui/icons.def"
#undef MESH_ICON_ENTRY
    MESH_UI_ICON_COUNT
};

/*
 * Sprite data, in the shape emoji.h uses for the same reason: flat runs, so a sprite that is
 * mostly one value costs a handful of bytes rather than 256.
 *
 * Runs are (count, alpha) pairs; icon N's runs are [run_offsets[N], run_offsets[N + 1]). Each
 * icon's runs cover exactly MESH_UI_ICON_SIZE * MESH_UI_ICON_SIZE pixels, row by row.
 */
struct mesh_ui_icon_table {
    const uint8_t *runs;
    const uint32_t *run_offsets; /* MESH_UI_ICON_COUNT + 1 entries */
};

extern const struct mesh_ui_icon_table mesh_ui_icon_table;

/*
 * Expand `icon` into one coverage value per pixel, row by row, 0 to MESH_UI_ICON_MAX_ALPHA.
 *
 * Decoded once and then sampled, rather than the runs being walked per pixel. An unknown icon
 * - and MESH_UI_ICON_NONE - fills `out` with zeroes, so a caller never has to test first.
 */
void mesh_ui_icon_alpha(enum mesh_ui_icon icon, uint8_t out[MESH_UI_ICON_SIZE * MESH_UI_ICON_SIZE]);

/*
 * The glyph name behind an icon: "chevron_right", "link_off".
 *
 * Diagnostics, tests and the generator, never a screen - it names a shape in a font rather than
 * anything a person reads, which is why it is not in the string catalog. Empty for
 * MESH_UI_ICON_NONE and for an id out of range.
 */
const char *mesh_ui_icon_name(enum mesh_ui_icon icon);

/* Whether `icon` names something this build can draw. MESH_UI_ICON_NONE is not one: it is the
   absence of an icon, which is legal everywhere and drawable nowhere. */
bool mesh_ui_icon_is_valid(enum mesh_ui_icon icon);

#ifdef __cplusplus
}
#endif

#endif /* MESH_UI_ICON_H */
