#pragma once

/*
 * The Settings tab as data: a list of sections, each a list of items with a label, a value
 * already formatted for display, and a kind. Backends draw the list; the nav walks it.
 *
 * An item that can be changed names its `field`. The nav keeps pending edits per field (in
 * `struct mesh_ui_nav`) and this module renders them in place of the radio's value, marked
 * dirty, until the app writes them (docs/settings-roadmap.md, phase 2). Everything about a
 * field the nav needs to edit it blind - its kind, enum names, number presets, text cap - is
 * answered here so the nav never has to know what a field means.
 */

#include "mesh/ui/store.h"

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum mesh_ui_settings_section {
    /* This client, not the radio: version, where its data lives, and the self-update rows.
       First because it is the one section that means anything without a connection. */
    MESH_UI_SETTINGS_ABOUT = 0,
    MESH_UI_SETTINGS_RADIO, /* firmware, hardware, node number */
    MESH_UI_SETTINGS_USER,
    MESH_UI_SETTINGS_DEVICE,
    MESH_UI_SETTINGS_DISPLAY,
    MESH_UI_SETTINGS_LORA,
    MESH_UI_SETTINGS_BLUETOOTH,
    MESH_UI_SETTINGS_CHANNELS,
    MESH_UI_SETTINGS_SECURITY,
    MESH_UI_SETTINGS_POSITION,
    MESH_UI_SETTINGS_POWER,
    MESH_UI_SETTINGS_MQTT,
    MESH_UI_SETTINGS_STORE_FORWARD,
    MESH_UI_SETTINGS_TELEMETRY,
    MESH_UI_SETTINGS_SECTION_COUNT,
};

enum mesh_ui_setting_kind {
    MESH_UI_SETTING_INFO = 0, /* read-only fact */
    MESH_UI_SETTING_TOGGLE,
    MESH_UI_SETTING_ENUM,
    MESH_UI_SETTING_TEXT,
    MESH_UI_SETTING_NUMBER,
    MESH_UI_SETTING_KEY,
    MESH_UI_SETTING_ACTION,
};

/* Editable settings. Each is one protobuf field; app.c turns an edit back into the protobuf
   (mesh_app_apply_setting_edit) and this module knows how to show and step it. */
enum mesh_ui_setting_field {
    MESH_UI_FIELD_NONE = 0,
    MESH_UI_FIELD_USER_LONG_NAME,
    MESH_UI_FIELD_USER_SHORT_NAME,
    MESH_UI_FIELD_USER_LICENSED,
    MESH_UI_FIELD_USER_UNMESSAGEABLE,
    MESH_UI_FIELD_DEVICE_TZDEF, /* text: a POSIX TZ string, e.g. AST4 or EST5EDT,M3.2.0,M11.1.0 */
    MESH_UI_FIELD_DISPLAY_SCREEN_ON,
    MESH_UI_FIELD_DISPLAY_CAROUSEL,
    MESH_UI_FIELD_DISPLAY_COMPASS,
    MESH_UI_FIELD_DISPLAY_12H,
    MESH_UI_FIELD_DISPLAY_UNITS,
    MESH_UI_FIELD_DISPLAY_FLIP,
    MESH_UI_FIELD_SF_ENABLED,
    MESH_UI_FIELD_SF_HEARTBEAT,
    MESH_UI_FIELD_SF_SERVER,
    MESH_UI_FIELD_TELEMETRY_DEVICE,
    MESH_UI_FIELD_TELEMETRY_INTERVAL,
    MESH_UI_FIELD_TELEMETRY_ENVIRONMENT,
    MESH_UI_FIELD_TELEMETRY_ENV_SCREEN,
    MESH_UI_FIELD_TELEMETRY_ENV_FAHRENHEIT,
    MESH_UI_FIELD_TELEMETRY_AIR_QUALITY,
    MESH_UI_FIELD_TELEMETRY_POWER,
    MESH_UI_FIELD_CHANNEL_NAME,
    MESH_UI_FIELD_CHANNEL_ROLE, /* enum: 0 disabled, 1 secondary; the primary slot is read-only */
    MESH_UI_FIELD_CHANNEL_KEY,  /* kind KEY: number is an enum mesh_ui_psk_choice */
    MESH_UI_FIELD_CHANNEL_UPLINK,
    MESH_UI_FIELD_CHANNEL_DOWNLINK,
    MESH_UI_FIELD_CHANNEL_POSITION,
    MESH_UI_FIELD_BT_ENABLED,
    MESH_UI_FIELD_BT_MODE,
    MESH_UI_FIELD_BT_PIN, /* text: six digits */
    MESH_UI_FIELD_LORA_REGION,
    MESH_UI_FIELD_LORA_USE_PRESET,
    MESH_UI_FIELD_LORA_PRESET,
    MESH_UI_FIELD_LORA_BANDWIDTH,
    MESH_UI_FIELD_LORA_SPREAD,
    MESH_UI_FIELD_LORA_CODING,
    MESH_UI_FIELD_LORA_HOPS,
    MESH_UI_FIELD_LORA_TX_ENABLED,
    MESH_UI_FIELD_LORA_TX_POWER, /* number: dBm, 0 = the radio's maximum */
    MESH_UI_FIELD_LORA_IGNORE_MQTT,
    MESH_UI_FIELD_LORA_OK_TO_MQTT,
    MESH_UI_FIELD_SECURITY_PRIVATE_KEY, /* KEY: keep / new random / typed (restore a backup) */
    MESH_UI_FIELD_SECURITY_ADMIN_KEY_0, /* KEY: keep / none / typed */
    MESH_UI_FIELD_SECURITY_ADMIN_KEY_1,
    MESH_UI_FIELD_SECURITY_ADMIN_KEY_2,
    MESH_UI_FIELD_SECURITY_MANAGED,
    MESH_UI_FIELD_SECURITY_ADMIN_CHANNEL,
    MESH_UI_FIELD_SECURITY_SERIAL,
    MESH_UI_FIELD_SECURITY_DEBUG_LOG,
    MESH_UI_FIELD_SECURITY_SIGNATURE_POLICY,
    MESH_UI_FIELD_COUNT,
};

/* What an ACTION row does when A is pressed. Rows of kind MESH_UI_SETTING_ACTION carry one in
   `number`, so the nav can raise the right action without knowing what the section means. */
enum mesh_ui_settings_action {
    MESH_UI_SETTINGS_ACTION_NONE = 0,
    MESH_UI_SETTINGS_ACTION_CHECK_UPDATE,
    MESH_UI_SETTINGS_ACTION_INSTALL_UPDATE,
};

/* What a KEY edit asks for. KEEP is the radio's current key (no edit); TYPED carries hex in
   the edit's text. The random choices are generated by the app when the write is built. */
enum mesh_ui_psk_choice {
    MESH_UI_PSK_KEEP = 0,
    MESH_UI_PSK_DEFAULT,    /* the one-byte "default key" shorthand */
    MESH_UI_PSK_RANDOM_128, /* new random AES-128 */
    MESH_UI_PSK_RANDOM_256, /* new random AES-256 */
    MESH_UI_PSK_NONE,       /* no encryption */
    MESH_UI_PSK_TYPED,
    MESH_UI_PSK_CHOICE_COUNT,
};
#define MESH_UI_PSK_CHOICE_BIT(choice) (1U << (unsigned)(choice))

#define MESH_UI_SETTINGS_LABEL_MAX 24U
#define MESH_UI_SETTINGS_VALUE_MAX 48U
#define MESH_UI_SETTINGS_ITEMS_MAX 16U

struct mesh_ui_settings_item {
    char label[MESH_UI_SETTINGS_LABEL_MAX];
    char value[MESH_UI_SETTINGS_VALUE_MAX];
    enum mesh_ui_setting_kind kind;
    enum mesh_ui_setting_field field;    /* NONE: read-only */
    bool dirty;                          /* value shown is a pending edit */
    uint32_t number;                     /* toggle 0/1, enum index, raw number, or key choice */
    char text[MESH_UI_SETTING_TEXT_MAX]; /* TEXT: the raw string; KEY: the key as hex */
};

const char *mesh_ui_settings_section_name(enum mesh_ui_settings_section section);

/* Field descriptions for the nav and the keyboard title. */
const char *mesh_ui_settings_field_label(enum mesh_ui_setting_field field);
enum mesh_ui_setting_kind mesh_ui_settings_field_kind(enum mesh_ui_setting_field field);
enum mesh_ui_settings_section mesh_ui_settings_field_section(enum mesh_ui_setting_field field);
/* ENUM fields: how many values and their names. */
uint32_t mesh_ui_settings_enum_count(enum mesh_ui_setting_field field);
const char *mesh_ui_settings_enum_name(enum mesh_ui_setting_field field, uint32_t value);
/* NUMBER fields step through a preset list: the next preset above (delta > 0) or below
   (delta < 0) `value`, or `value` itself at either end. */
uint32_t mesh_ui_settings_number_step(enum mesh_ui_setting_field field, uint32_t value, int delta);
/* TEXT fields: the longest value the radio accepts, in bytes without the NUL. */
uint32_t mesh_ui_settings_text_max(enum mesh_ui_setting_field field);

/* Sections whose write can cut this client off or the radio off the mesh (Bluetooth:
   re-pairing; Channels: a changed key; LoRa: region and preset; Security: identity and
   managed mode). The nav asks before saving them; `confirm_text` is what the overlay says. */
bool mesh_ui_settings_section_needs_confirm(enum mesh_ui_settings_section section);
void mesh_ui_settings_confirm_text(enum mesh_ui_settings_section section, char *out,
                                   size_t out_len);

/* KEY fields: which choices Left/Right offer (a bitmask of MESH_UI_PSK_CHOICE_BIT), and
   whether a key of `len` bytes is acceptable for the field. */
uint32_t mesh_ui_settings_key_choices(enum mesh_ui_setting_field field);
bool mesh_ui_settings_key_len_ok(enum mesh_ui_setting_field field, size_t len);

/* Keys as text. key_text() is base64, what the Meshtastic apps show and accept, so a key
   read off the Brick can be typed into a phone and vice versa. parse() takes base64 or hex
   (an even number of hex digits); an empty string is an empty key. */
void mesh_ui_settings_key_text(const uint8_t *key, size_t len, char *out, size_t out_len);
void mesh_ui_settings_key_hex(const uint8_t *key, size_t len, char *out, size_t out_len);
bool mesh_ui_settings_key_parse(const char *text, uint8_t *out, size_t out_cap, size_t *out_len);

/* The channel slot behind row `row` of the Channels list, or -1. */
int mesh_ui_settings_channel_at_row(const struct mesh_ui_settings *settings,
                                    const struct mesh_ui_handshake_state *handshake, uint32_t row);

/* The pending edit for `field` among `edits`, or NULL. */
const struct mesh_ui_setting_edit *
mesh_ui_settings_find_edit(const struct mesh_ui_setting_edit *edits, size_t edit_count,
                           enum mesh_ui_setting_field field);

/* Whether the radio has sent the data this section shows. `handshake` may be NULL (no radio);
   it is only consulted for the Channels and Radio sections. */
bool mesh_ui_settings_section_loaded(const struct mesh_ui_settings *settings,
                                     const struct mesh_ui_handshake_state *handshake,
                                     enum mesh_ui_settings_section section);

/* Items in a section for the current data. Zero when the section has not loaded. `channel`
   is the open slot in the Channels section, MESH_UI_SETTINGS_NO_CHANNEL otherwise. */
uint32_t mesh_ui_settings_item_count(const struct mesh_ui_settings *settings,
                                     const struct mesh_ui_handshake_state *handshake,
                                     enum mesh_ui_settings_section section, uint8_t channel);

/* Describes one row, with pending `edits` (may be NULL) shown in place of the radio's values.
   Returns false when `row` is out of range. */
bool mesh_ui_settings_item(const struct mesh_ui_settings *settings,
                           const struct mesh_ui_handshake_state *handshake,
                           const struct mesh_ui_setting_edit *edits, size_t edit_count,
                           enum mesh_ui_settings_section section, uint8_t channel, uint32_t row,
                           struct mesh_ui_settings_item *out);

#ifdef __cplusplus
}
#endif
